name: stormkit-cli run test

on: push

jobs:

  build:
    name: Unit-Testing
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.15
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Running Tests
      run: go test -v ./...
